#!/bin/sh /etc/rc.common
# OpenSpeedTest - OpenWrt Init Script
# Generates test files in /tmp (RAM) on router boot.
# Install to: /etc/init.d/speedtest-init
# Enable:     service speedtest-init enable
#             service speedtest-init start

START=99
STOP=10
NAME=speedtest-init

DL_FILE="/tmp/downloading"
UL_FILE="/tmp/upload"
DL_SIZE_MB=50
WWW_DIR="/www"

start() {
    logger -t speedtest-init "Generating ${DL_SIZE_MB}MB download test file in /tmp ..."

    # Generate download test file from /dev/urandom (realistic, non-compressible)
    dd if=/dev/urandom of="$DL_FILE" bs=1048576 count=$DL_SIZE_MB 2>/dev/null

    # Create empty upload sink file
    : > "$UL_FILE"

    # Create symlinks in webroot so uhttpd serves them at /downloading and /upload
    [ -L "${WWW_DIR}/downloading" ] || ln -sf "$DL_FILE" "${WWW_DIR}/downloading"
    [ -L "${WWW_DIR}/upload" ]      || ln -sf "$UL_FILE" "${WWW_DIR}/upload"

    logger -t speedtest-init "Done. Symlinks created in ${WWW_DIR}."
}

stop() {
    # Remove symlinks and temp files on stop/reboot
    rm -f "${WWW_DIR}/downloading" "${WWW_DIR}/upload"
    rm -f "$DL_FILE" "$UL_FILE"
    logger -t speedtest-init "Cleaned up speedtest temp files."
}

restart() {
    stop
    start
}
